<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Abstractions\BuildingBlocks.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Modules\Users\Users.Application\Users.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Users\Users.Domain\Users.Domain.csproj" />
    <ProjectReference Include="..\..\src\Gateway\WebApi\Gateway.WebApi.csproj" />
    <ProjectReference Include="..\Shared.Testing\Shared.Testing.csproj" />
  </ItemGroup>

</Project>
